name: Build LaTeX document
on: [push]
permissions:
  contents: write
  discussions: write
jobs:
  build_latex:
    runs-on: ubuntu-latest
    continue-on-error: true
    env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - name: Set up Git repository
        uses: actions/checkout@v3
      - name: Compile LaTeX document
        uses: xu-cheng/latex-action@v3
        with:
          root_file: document.tex
          extra_system_packages: "inkscape"
          args: -f -jobname=document -pdf -file-line-error -shell-escape -interaction=nonstopmode -synctex=1
      - name: Upload PDF file
        if: always()
        uses: actions/upload-artifact@v3
        with:
          name: PDF
          path: document.pdf
      # - name: Create Release
      #   id: create_release
      #   uses: actions/create-release@v1
      #   env:
      #     GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # This token is provided by Actions, you do not need to create your own token
      #   with:
      #     tag_name: ${{ github.ref }}
      #     release_name: Build ${{ github.ref }}
      #     body: |
      #       New build
      #     draft: false
      #     prerelease: false
      # # Прикладываемые файлы надо заливать отдельным step
      # - name: Upload pdf asset
      #   uses: actions/upload-release-asset@v1
      #   env:
      #     # Тоже требуется токен
      #     GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      #   with:
      #     # Из предыдущего step с id=create_release генерится upload_url — по нему и надо заливать
      #     upload_url: ${{ steps.create_release.outputs.upload_url }}
      #     # Не переходим в папку latex_sources, поскольку download-artifacts грузит в текущую директорию
      #     asset_path: ./document.pdf
      #     # Имя, которое будет высвечиваться в релизе
      #     asset_name: document.pdf
      #     asset_content_type: application/pdf
      - name: Release with Notes
        uses: softprops/action-gh-release@v1
        if: always()
        with:
          name: Build
          body: build
          tag_name: pdf
          files: |
            document.pdf
      # - name: Publish HTML to GitHub Pages
      #   uses: peaceiris/actions-gh-pages@v3
      #   if: always()
      #   with:
      #     github_token: ${{ secrets.GITHUB_TOKEN }}
      #     publish_dir: /
